#!/usr/bin/bash
rm minifs.lua
ldoc -d doc .
moonc minifs.moon
if [ "$1" = "-c" ]; then
        if [ -z "$2" ]; then
                echo "Need argument (commit message)!" 1>&2
                exit 1
        fi
        git add .
        git commit -m "$2"
        git push
fi
